baseURL: "https://marekwiewiorka.org/"
title: Marek Wiewi贸rka
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
        - name: Talks
          url: talks/
          weight: 4
        - name: Software
          url: software/
          weight: 5


params:
    description: "I am an Assistant Professor in the Institute of Computer Science at the Warsaw University of Technology."
    author: Marek Wiewi贸rka
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","teaching","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Marek Wiewi贸rka, PhD
          subtitle: "I am an Assistant Professor in the **[Institute of Computer Science](https://www.ii.pw.edu.pl/)** at the **[Warsaw University of Technology](https://eng.pw.edu.pl/)** and a Chief Architect at **[GetInData | part of Xebia ](https://getindata.com/)**. My research focuses on design and application of *distributed systems*, *artificial intelligence* and *cloud computing* for large scale **genomic** studies."
          imageUrl: "gravel_round.jpeg"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: Publications
              url: papers/
            - name: Teaching
              url: courses/
            - name: Talks
              url: talks/
            - name: Software
              url: software/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Email
          url: mailto:marek.wiewiorka@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/marekwiewiorka/
        - name: Google Scholar
          url: https://scholar.google.pl/citations?user=S5lOB_AAAAAJ
        - name: GitHub
          url: https://github.com/mwiewior

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Marek Wiewi贸rka"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2